### ISSUE TITLE
add language translation

### ISSUE THREAD

**Issue by ga2arch** [dustin/twitterspy#12]
could be interesting try to add a language translation for tweets :)

**Comment by dustin** [comment]
I've been thinking about this, yeah.  It'd be quite awesome.

A long time ago, twitterspy allowed you to specify your language preference and would use that to limit your searches to within that language.  The API does claim to know what language things were written in.

If you can find a simple translation API, it should be quite easy to fit it in.

**Comment by dustin** [comment]
Language translation gets particularly difficult due to twitter not cluing me in on the source language.  I'd rather not run every tweet through translation just in case it's not in the target language.
