### ISSUE TITLE
'watch_friends' poorly documented

### ISSUE THREAD

**Issue by cwb** [dustin/twitterspy#19]
'help' says the following:

```
watch_friends   Enable or disable watching friends.
```

and 'watch_friends enable' results in:

```
Arguments required for watch_friends:
Enable or disable watching friends.
```

But I gave it an argument! This was maddening until I figured out that it wanted 'watch_friends on.'

Please clarify the help text to specify the correct arguments. Thanks!

**Comment by dustin** [comment]
Updated.  Thanks.
