### ISSUE TITLE
mood on/off

### ISSUE THREAD

**Issue by sattellite** [dustin/twitterspy#20]
I don't want recieve moods. It would be better if you will be able to disable them.

**Comment by dustin** [comment]
I can't do much about this.  It's not sending it to _you_, it's sending it to its xmpp server.  Your client is a subscriber to this message.  Your best bet if you don't want it is to have your client unsubscribe from those messages.

See the following for protocol details:

http://xmpp.org/extensions/xep-0107.html

**Comment by sattellite** [comment]
Thanks for answer.
