### ISSUE TITLE
untrack gent not working.

### ISSUE THREAD

**Issue by blueintray** [dustin/twitterspy#21]
I can't stop tracking the word Gent.  As you can see from the log I've Tried track and then untrack.  A real pain because "gent" appears frequently in foreign language tweets:

(10:17:29 AM) im@twitterspy.org: Tracking Gent
(10:17:31 AM) im@twitterspy.org: Stopped tracking Gent
(10:17:38 AM) <myid>@gmail.com/DD181300: track gent
(10:17:38 AM) im@twitterspy.org: Tracking gent
(10:17:43 AM) <myid>@gmail.com/DD181300: untrack gent
(10:17:43 AM) im@twitterspy.org: Stopped tracking gent
(10:23:49 AM) im@twitterspy.org: JordiCartanya: Seguim amb el dia de trobades, xerrades i reunions amb diversa gent de cara a les eleccions

**Comment by dustin** [comment]
Is this still happening for you?

**Comment by blueintray** [comment]
Problem seems to have gone away.  Yesterday, "Gent" appeared in the list returned by the tracks command and so I ran "untrack Gent", again.  No messages with Gent or gent seen since.

Was something changed on the server?

**Comment by blueintray** [comment]
Spoke too soon.  I'm having the same problem with untracking Harman.

**Comment by dustin** [comment]
_sigh_ -- well, there's a bug in stopping tracks somewhere.  I haven't isolated it.  It doesn't come _back_ when you restart, but it doesn't go away when you untrack.  :(

Unfortunately, I haven't been able to put much time into this thing lately.  I have a couple bugs I'd really like to kill, but am (un?)fortunately being successful in my startup.

**Comment by blueintray** [comment]
Might it have something to do with the case of the text entered to track, e.g. antwertpen and Antwerpen.  Or are tracks case insensitive?

The redintray [at] gmail... Twitterspy account  is currently tracking "Harman", "Antwerpen" and "airbrush" but these don't show up with the tracks command.  I can't remember if tracked "airbrush" or "Airbrush", though.

p.s. This issue is currently marked closed, not sure how to re-open it in github.
